### PR TITLE
search functionality

### LINKED ISSUE #27: API for search users
API for search users based on their name /email.

and return users along with their profile image

### PR DESCRIPTION
**Pull request by Bhavyajain21**
/claim #27 
/fixes #27

### CODE REVIEW

**Comment by Bhavyajain21** [comment]
please review @hsb1007

**Comment by hsb1007** [comment]
Thank you, is there reason why it was done in Auth instead of User?

**Comment by hsb1007** [comment]
@Bhavyajain21 ?

**Comment by Bhavyajain21** [comment]
Hey, It's possible that the initial focus of the application was on authentication, and search functionality was added later. Placing it in AuthService might have been a quick solution at the time, without considering a more appropriate location.

**Comment by Bhavyajain21** [comment]
Thanks @hsb1007, On to the next one! 🚀

**Pull request merged**
