### PR TITLE
feat(api): Add user rating

### LINKED ISSUE #26: API to leave comments for users
image

As an authenticated user, you can leave review for other users along with star ratings for 

- Professionalism
- Reliability
- Communication

And one thing missing from the screenshot is a boolean value to mark the review submitter as anonymous

### PR DESCRIPTION
**Pull request by rajdip-b**
Fixes #26
/claim #26

### CODE REVIEW

**Comment by hsb1007** [comment]
Thank you, the other PR has better error handling hence I am going with the other one!

**Comment by rajdip-b** [comment]
Okay sure!

**Comment by rajdip-b** [comment]
Hey @hsb1007, there is no other PR. might this be an overlook?

**Comment by hsb1007** [comment]
wait 
sorry this is wrong PR i closed!

**Comment by rajdip-b** [comment]
haha no worries!

**Pull request merged**
